name: GitHub Actions Demo
on: [push]
jobs:
  run-e2e-test:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - shell: bash
        env:
          GOOGLE_USERNAME: ${{ secrets.GOOGLE_USERNAME }}
          GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}
        run: |
          printf '{
            "username": "%s",
            "password": "%s"
          }' "$GOOGLE_USERNAME" "$GOOGLE_PASSWORD" > test/test-creds.json
      - run: npm ci
      - run: npm test
